In [1]:
import torch
print(torch.__version__)

2.7.0


In [2]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU.")
else:
    print("CUDA is not available. Using CPU.")

CUDA is not available. Using CPU.


In [3]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
s = torch.rand(2,3)*10

In [ ]:
torch.manual_seed(100)  # used to get same output of randome function
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [43]:
torch.manual_seed(100)
s =torch.rand(2,3)

In [15]:
torch.tensor([[1,2,3],[5,6,7]])

tensor([[1, 2, 3],
        [5, 6, 7]])

In [ ]:
# same functions like numpy 
# linspace
# arange
# torch.eye, identity matrix

# ((Shape),element)
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [17]:
torch.ones(3,3)*5

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

Shape Tensor

In [28]:
x = torch.tensor([[1,2,30],[8,5,9]])
x.shape

torch.Size([2, 3])

In [25]:
torch.empty_like(x) 
# to copy the shape of another matrix0

tensor([[0, 0, 0],
        [0, 0, 0]])

In [26]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [35]:
torch.tensor([1.,2.,3.],dtype=torch.int64)

tensor([1, 2, 3])

In [38]:
# mathematical operations
# we can apply tensor + scaler
x +2

tensor([[ 3,  4, 32],
        [10,  7, 11]])

In [39]:
a = torch.linspace(-10,10,11)

In [41]:
a + 2

tensor([-8., -6., -4., -2.,  0.,  2.,  4.,  6.,  8., 10., 12.])

In [42]:
torch.abs(a)

tensor([10.,  8.,  6.,  4.,  2.,  0.,  2.,  4.,  6.,  8., 10.])

In [48]:
torch.round(s)
# rounding up the number

tensor([[0., 1., 0.],
        [0., 1., 1.]])

In [49]:
torch.floor(s)
# give behind integer value

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [50]:
torch.ceil(s)
# give forword integer value

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [51]:
# clamp
torch.clamp(a,min=4,max=10)

tensor([ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  6.,  8., 10.])