In [4]:
import torch
import torch.nn as nn

class Model(nn.Module):
    
    def __init__(self,num_feature):
        super().__init__()  # parent class (nn.Module) ke constructure ko invoke kar rahe hai
        # layer
        self.linear = nn.Linear(num_feature,1) # num_feature is a input & output as single neuron
        self.sigmoid = nn.Sigmoid()
       
    # forword pass 
    def forward(self,feature):
        out = self.linear(feature)  # z = w*x+b
        out = self.sigmoid(out)     # a = sigmoid(z)
        return out

In [7]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)
# yethe ek __call__ function override zale ahe
# tyamule model(features) as a function call kela tar forward pass execute hote

tensor([[0.5831],
        [0.5880],
        [0.6528],
        [0.6055],
        [0.6723],
        [0.6162],
        [0.6210],
        [0.5986],
        [0.6354],
        [0.6307]], grad_fn=<SigmoidBackward0>)

In [10]:
# show model weights
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[ 0.1963, -0.2138,  0.3069,  0.0298,  0.0104]], requires_grad=True)
Parameter containing:
tensor([0.3194], requires_grad=True)


In [13]:
!pip install torchinfo

In [14]:
from torchinfo import summary

In [16]:
summary(model,input_size=(10,5))
# 6 trainable parameter ahet :: 5 weights + 1 bias

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00