In [1]:
import torch
import torch.nn as nn

class Model(nn.Module):
    
    def __init__(self,num_feature):
        
        super().__init__()
        self.linear1 = nn.Linear(num_feature,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,feature):
        
        out = self.linear1(feature)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [ ]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.3530],
        [0.3722],
        [0.3760],
        [0.3698],
        [0.3544],
        [0.3698],
        [0.3428],
        [0.3822],
        [0.3671],
        [0.3623]], grad_fn=<SigmoidBackward0>)

In [4]:
# show model weights
print(model.linear1.weight)
print(model.linear1.bias)

# show model weights
print(model.linear2.weight)
print(model.linear2.bias)

Parameter containing:
tensor([[-0.2358,  0.3457,  0.0968, -0.3772,  0.0291],
        [ 0.0100, -0.1266, -0.1070,  0.3250,  0.0208],
        [ 0.0347,  0.1287, -0.1734,  0.0562, -0.1805]], requires_grad=True)
Parameter containing:
tensor([ 0.3281, -0.1458,  0.4041], requires_grad=True)
Parameter containing:
tensor([[-0.3294,  0.3302,  0.1952]], requires_grad=True)
Parameter containing:
tensor([-0.5423], requires_grad=True)


In [9]:
from torchinfo import summary

In [10]:
summary(model,input_size=(10,5))
# 6 trainable parameter ahet :: 5 weights + 1 bias

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00