In [1]:
import torch
from sklearn.datasets import make_classification

In [2]:
# create a synthetic dataset
X,y = make_classification(
            n_samples=10, #number of samples
            n_features=2,  #number of features
            n_classes=2,   #number of classes
            n_informative=2, #number of informative features
            n_redundant=0,   #number of redundant features  
            random_state=42 # for reproducibility
    )

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [5]:
# convert the data to pytorch tensors
x = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)  

In [7]:
from torch.utils.data import Dataset, DataLoader

In [8]:
class customDataset(Dataset):
    def __init__(self,feature,labels):
        self.feature = feature
        self.labels = labels
    
    def __len__(self):
        return self.feature.shape[0]
    
    def __getitem__(self, index):
        return self.feature[index], self.labels[index]

In [9]:
dataset = customDataset(x,y)

In [12]:
len(dataset)
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [16]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [17]:
for batch_features, batch_labels in dataloader:
    print(batch_features, batch_labels)
    print("---")

tensor([[-1.9629, -0.9923],
        [ 1.7273, -1.1858]]) tensor([0, 1])
---
tensor([[-2.8954,  1.9769],
        [-1.1402, -0.8388]]) tensor([0, 0])
---
tensor([[ 1.7774,  1.5116],
        [-0.5872, -1.9717]]) tensor([1, 0])
---
tensor([[ 1.0683, -0.9701],
        [-0.7206, -0.9606]]) tensor([1, 0])
---
tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]]) tensor([1, 1])
---


In [ ]:
# ata he kam ek zalyanantar dusare hot ahe tyamule jar datset motha aala atr vel lagnar
# tyamule ata he kam parallel karaycha ahe
# mhunun aaplyalala dataloader madhe num_workers = 2 asa option dya


in pytorch the sampler int the dataloader determines the strategy for selecting samples from the dataset during data loading. It controls how indices of the datset are drawn for each batch.   

types of sampler :
1. sequential  (shuffle = False)
2. randomSampler  (shuffle = True)

In [18]:
# collate_fn is a function that is used to collate the data in the dataloader
# or in other words a function that specifieshow to combine a list of samples from a daraset into a single batch/

imp parameters for dataloader ::

dataset(mandatory) -- dataset from which the dataloader will pull data  
batch_size -- how many samples per batch to load  
shuffle -- random shuffling  
num_worker -- parallel number of worker processes  
pin_memory -- related to gpu  
drop_last -- will used to drop_last batch which was form with irregular size   
collate_fn   
sampler   