In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
# simple Linear regression

class meraLR:
    def __init__(self):
        self.m = None
        self.b = None
        
    # to train the model
    def fit(self,X_train,y_train):
        num = 0
        dem =0
        for i in range(X_train.shape[0]):
           num  = num + ( X_train[i] - X_train.mean()) * (y_train[i]- y_train.mean())
           dem =  dem + ( X_train[i] - X_train.mean()) * (X_train[i]- X_train.mean())
            
           self.m = num / dem
           self.b = y_train.mean() - self.m*X_train
           
           print(self.m)
           print(self.b)
           
    
    def predict(self,X_test):
        print(X_test)
        return self.m * X_test - self.b
    
    # linear regression mai model ko train karna matlab m and b ki value find karna

In [38]:
df = pd.read_csv('placement.csv')

In [39]:
df.head()

,CGP,Package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [40]:
x = df.iloc[:,0].values  # numpy array
y = df.iloc[:,1].values #numpy array

In [41]:
X_train ,X_test,y_train,y_teat = train_test_split(x,y,test_size=0.2,random_state=2)

In [42]:
X_train.shape

(4,)

In [43]:
lr = meraLR()

In [44]:
lr.fit(X_train,y_train)

1.2949640287769784
[-5.86705036 -3.51021583 -6.48863309 -5.80230216]
0.8016666575652164
[-2.4435666  -0.98453329 -2.8283666  -2.40348327]
0.7701170442388974
[-2.22461229 -0.82299927 -2.59426847 -2.18610643]
0.7614600256345365
[-2.16453258 -0.77867533 -2.53003339 -2.12645958]


In [45]:
X_train ,X_test,y_train,y_teat = train_test_split(x,y,test_size=0.2,random_state=2)


In [46]:
lr.fit(X_train,y_train)

1.2949640287769784
[-5.86705036 -3.51021583 -6.48863309 -5.80230216]
0.8016666575652164
[-2.4435666  -0.98453329 -2.8283666  -2.40348327]
0.7701170442388974
[-2.22461229 -0.82299927 -2.59426847 -2.18610643]
0.7614600256345365
[-2.16453258 -0.77867533 -2.53003339 -2.12645958]


In [47]:
print(lr.predict(X_test[0]))

7.82
[8.11914998 6.73329273 8.48465079 8.08107698]


In [ ]:
lr.