Numpy Methods


In [2]:
import numpy as np
#1d array
a = np.array([1,2,3])
print(a)
print(type(a))
#vector

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
#matrix
# 2d array

[[1 2 3]
 [4 5 6]]


In [ ]:
c  = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
# 3d array
# tensor

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# dtype
np.array([1,2,3],dtype=float)
np.array([1,0,3],dtype=bool)

array([ True, False,  True])

In [11]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
np.arange(1,11,2) #to create array

array([1, 3, 5, 7, 9])

In [29]:
np.arange(1,11).reshape(2,5) #you have to think when you want to change its size

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# np.random
np.random.random((3,4))*10

array([[4.79611197, 5.82372192, 8.07413549, 1.20083628],
       [6.98960033, 9.21686711, 5.58261043, 3.96544566],
       [6.99849171, 9.48369863, 4.40225778, 5.18528017]])

In [38]:
np.linspace(-10,10,5) #(lower range,upper range,total number)

array([-10.,  -5.,   0.,   5.,  10.])

In [15]:
#  np.identity
np.identity(3)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [17]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a3.ndim  #gives number of dimesions
a3.shape
a3.size
a3.itemsize

8

In [24]:
a3.dtype

dtype('int64')

Changing Datatype


In [64]:
a3.astype('float32').astype('int32')
a3.astype('int32')

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations


In [69]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
# scalar operations(+,-,*,/)
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [29]:
#relational
a2>=10
a2[a2 >=10]

array([10., 11.])

In [102]:
# vector operations
# a1*a2
np.dot(a1,a2)

array([[1472., 1570., 1668., 1766.],
       [2860., 3039., 3218., 3397.],
       [1044., 1104., 1164., 1224.]])

Array Functions

In [33]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[37., 71.,  5.],
       [58., 62.,  0.],
       [41., 85., 40.]])

In [34]:
# min/max/sum/prod
# 0 -> col and 1 -> row
np.min(a1,axis=0)
np.min(a1,axis=1)

array([ 5.,  0., 40.])

In [35]:
# mean/median/std/var
np.mean(a1,axis=1)
np.median(a1,axis=0)

array([41., 71.,  5.])

In [36]:
#trigo function
np.sin(a1[2])

array([-0.15862267, -0.17607562,  0.74511316])

In [41]:
np.dot(a1,a2)
print(a1)
print(a2)

[[37. 71.  5.]
 [58. 62.  0.]
 [41. 85. 40.]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [105]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [106]:
np.exp(a1)

array([[2.90488497e+13, 1.14200739e+26, 1.09663316e+03],
       [1.73927494e+18, 4.92345829e+41, 6.39843494e+17],
       [1.62754791e+05, 3.26901737e+06, 2.14643580e+14]])

In [107]:
# round/floor/ceil
np.round(a1)

array([[31., 60.,  7.],
       [42., 96., 41.],
       [12., 15., 33.]])

In [108]:
np.floor(a1)

array([[31., 60.,  7.],
       [42., 96., 41.],
       [12., 15., 33.]])

In [43]:
np.round(np.random.random((2,3))).astype('int')*100

array([[100,   0,   0],
       [  0,   0,   0]])