Indexing and Slicing

In [1]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [2]:
# indexing
a1[len(a1)-1]

np.int64(9)

In [3]:
a2[2,2]
a2[2][2]
a2
# both are valid cases

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a1[2:5:2] #slicing

array([2, 4])

Iterating


In [6]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a2[0,:]
a2[1,:2]
a2[:,2]
# a2[row,:col]
# a2[row,:]
# a2[:,col]

array([ 2,  6, 10])

In [8]:
a2[1:,1:3]
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [10]:
a2[1,::3]

array([4, 7])

In [11]:
a2[:2:,1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
a3[1,:,2]

array([11, 14, 17])

In [14]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [15]:
a3[::2,:1:,::2]

array([[[ 0,  2]],

       [[18, 20]]])

Iterating

In [16]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
a2
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [18]:
a3
for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [19]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


Reshaping

In [20]:
#reshape
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [25]:
a3.ravel()
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Stacking

In [27]:
# horizaontaly
a4 = np.arange(4).reshape(2,2)
a5 = np.arange(4,8).reshape(2,2)

np.hstack((a4,a5))
np.vstack((a4,a5))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

Spliting

In [23]:
a6 = np.arange(8).reshape(4,2)
np.hsplit(a6,2)
np.vsplit(a6,2)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]])]