Numpy Array vs Python Lists

In [1]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c =[]
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
    
print(time.time()-start)

2.514678478240967


In [2]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print(time.time()-start)

0.1853489875793457


In [3]:
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [4]:
a = np.arange(10000000)
sys.getsizeof(a)

80000112

In [5]:
# convience
a = np.arange(10000000)
start = time.time()
time.time() - start

7.82012939453125e-05

In [6]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
# slicing and indexing
a[(1,2)]
a[1:3,1:]

array([[4, 5],
       [7, 8]])

In [28]:
# fancy indexing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a[[0,2,3]]   #row wise selection means 0,2,3 are denotes row
a[[0,2,3][1]]

# yacha arth tya row madhale 1 index la aslela row
 

array([ 8,  9, 10, 11])

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
a[[0,2,3,5]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [12]:
# fancy indexing
a[:,[0,2,3]]
# all rows ani tya madhale [0,2,3] la aslele columns

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [13]:
# boolean masking
a1 = np.random.randint(1,100,24).reshape(6,4)
a1

array([[ 6, 79, 57, 19],
       [97, 32, 74, 80],
       [88, 90, 77, 78],
       [29, 29, 20, 73],
       [31, 51, 36, 11],
       [58, 74, 19, 94]], dtype=int32)

In [14]:
#find all number which are greater than 50
a1[a1>50]

array([79, 57, 97, 74, 80, 88, 90, 77, 78, 73, 51, 58, 74, 94],
      dtype=int32)

In [15]:
#find even numbers
a1[a1%2==0]

array([ 6, 32, 74, 80, 88, 90, 78, 20, 36, 58, 74, 94], dtype=int32)

In [16]:
a1[(a1>50) & (a1%2==0)]

array([74, 80, 88, 90, 78, 58, 74, 94], dtype=int32)

In [17]:
a1[~(a1%7==0)] # ~ - not

array([ 6, 79, 57, 19, 97, 32, 74, 80, 88, 90, 78, 29, 29, 20, 73, 31, 51,
       36, 11, 58, 74, 19, 94], dtype=int32)

#Broadcasting

The term broacasting describes how numpy treats array with diff shapes during arithmatic operations. The smaller array is "Broadcasting " across the larger array so that they have  compatible shapes.


In [18]:
# same shape 
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [19]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [20]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [21]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

# print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


In [22]:
a = np.arange(6).reshape(2,3)
b = np.arange(1,2)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[1]
[[1 2 3]
 [4 5 6]]


In [23]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [24]:
a = np.array([1])
b = np.arange(4)

print(a)
print(b)
print(a+b)

[1]
[0 1 2 3]
[1 2 3 4]


In [25]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
c = np.hsplit(a,2)

print(a)
print(b)
print(c)
b+c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


ValueError: operands could not be broadcast together with shapes (2,2) (2,4,2) 

Working With Mathematical formulas