Numpy Array vs Python Lists

In [1]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c =[]
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
    
print(time.time()-start)

3.0734241008758545


In [7]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print(time.time()-start)

0.18832087516784668


In [8]:
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [9]:
a = np.arange(10000000)
sys.getsizeof(a)

80000112

In [10]:
# convience
a = np.arange(10000000)
start = time.time()
time.time() - start

9.34600830078125e-05

In [11]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
# slicing and indexing
a[(1,2)]
a[1:3,1:]

array([[4, 5],
       [7, 8]])

In [18]:
# fancy indexing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
a[[0,2,3]]   #row wise selection means 0,2,3 are denotes row
a[[0,2,3][1]]

# yacha arth tya row madhale 1 index la aslela row
 

array([ 8,  9, 10, 11])

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
a[[0,2,3,5]]
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# fancy indexing
a[:,[0,2,3]]
# all rows ani tya madhale [0,2,3] la aslele columns

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [33]:
# boolean masking
a1 = np.random.randint(1,100,24).reshape(6,4)
a1

array([[88, 73, 85, 70],
       [59, 81, 95, 58],
       [36, 18, 12, 57],
       [10, 32,  7, 75],
       [95, 75, 69, 64],
       [53, 71,  9, 55]], dtype=int32)

In [50]:
#find all number which are greater than 50
a1[a1>50]

array([65, 87, 72, 81, 99, 57, 95, 56, 79, 55, 74, 62, 94, 98, 55],
      dtype=int32)

In [54]:
#find even numbers
a1[a1%2==0]

array([22, 72, 10, 56, 74, 62, 44, 94, 98], dtype=int32)

In [61]:
a1[(a1>50) & (a1%2==0)]

array([72, 56, 74, 62, 94, 98], dtype=int32)

In [67]:
a1[~(a1%7==0)] # ~ - not

array([22, 65, 87, 72, 81, 10, 99, 57, 39, 95, 39, 79, 41, 55, 19, 74, 62,
       44, 94, 55, 15], dtype=int32)

#Broadcasting

The term broacasting describes how numpy treats array with diff shapes during arithmatic operations. The smaller array is "Broadcasting " across the larger array so that they have  compatible shapes.


In [70]:
# same shape 
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [76]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [79]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

# print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [87]:
a = np.arange(6).reshape(2,3)
b = np.arange(1,2)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[1]
[[1 2 3]
 [4 5 6]]


In [88]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [93]:
a = np.array([1])
b = np.arange(4)

print(a)
print(b)
print(a+b)

[1]
[0 1 2 3]
[1 2 3 4]


In [34]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [36]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
c = np.hsplit(a,2)

print(a)
print(b)
print(c)
b+c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


ValueError: operands could not be broadcast together with shapes (2,2) (2,4,2) 

Working With Mathematical formulas