In [2]:
import numpy as np

In [3]:
def fun(a,b):
    x = np.ones((a,b))
    x[1:-1,1:-1]=0
    return x
fun(8,9)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
np.linspace(0.1,0.9,12)
np.linspace(0.1,0.9,12)[1:-1]

array([0.17272727, 0.24545455, 0.31818182, 0.39090909, 0.46363636,
       0.53636364, 0.60909091, 0.68181818, 0.75454545, 0.82727273])

In [ ]:
# identity
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
a = np.ones((5,5))
a *= np.arange(5)
a


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [10]:
a = np.random.randint(1,100,(10,2))
p = np.array([2,3])
print(a)
print(p)

np.sqrt(np.sum((a-p)**2,axis=1)).astype(int)

[[46 23]
 [75 57]
 [60 29]
 [19 42]
 [ 8 55]
 [73 20]
 [34 97]
 [71 77]
 [12 70]
 [77  4]]
[2 3]


array([ 48,  90,  63,  42,  52,  73,  99, 101,  67,  75])

In [11]:
np.unravel_index(100,(6,7,8)) #unravel_index is used to find location of specific data in given matrix

np.ravel(a)

array([46, 23, 75, 57, 60, 29, 19, 42,  8, 55, 73, 20, 34, 97, 71, 77, 12,
       70, 77,  4], dtype=int32)

In [8]:
# a = input().strip().split()
a = [1,2,3,4,5]
a =np.array(a[::-1],dtype=float) #used to reverse a array
a

array([5., 4., 3., 2., 1.])

In [12]:
a = np.array([1,2,3,4,5,6])
print(len(a))
a.size

6


6

In [58]:
# used for deep learning
# softmax function
# softmax chya array chi sum 1 aste

def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Required Numpy Array")
    s= np.sum( np.exp(arr))
    return np.exp(arr) / s
softmax(np.arange(5))


array([0.01165623, 0.03168492, 0.08612854, 0.23412166, 0.63640865])

In [13]:
a = np.ones(25).reshape(5,5)
a *= np.arange(5)
print(a)
a = np.arange(20).reshape(4,5)
b = np.arange(20).reshape(4,5)
np.vstack((a,b))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
def vertical(*args):
    for i in args:
        if type(i) is not np.ndarray:
            raise TypeError("Required numpy array")
    return np.vstack(args)

a = np.arange(10).reshape(2,-1)
print("a:",a)
b = np.arange(10).reshape(2,-1)
print("b:",b)

print(vertical(a,b))
c = np.random.random((2,5))
print("c:",c)
vertical(a,b,c)

a: [[0 1 2 3 4]
 [5 6 7 8 9]]
b: [[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
c: [[0.49432097 0.07045489 0.82513756 0.92424117 0.59688601]
 [0.60437909 0.32199706 0.65119873 0.98055401 0.02392893]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [0.49432097, 0.07045489, 0.82513756, 0.92424117, 0.59688601],
       [0.60437909, 0.32199706, 0.65119873, 0.98055401, 0.02392893]])

In [ ]:
def date_array(start:str,end:str):
    if type(start) is not str or type(end) is not str:
        raise TypeError
    end = end.split("-")
    end[-1] = int(end[-1])+1
    end[-1] = 
    end = "-".join(end)
    return np.arange(start,end,dtype="datetime64[D]")

date_array(start='2022-12-01',end='2022-12-06')

TypeError: sequence item 2: expected str instance, int found

In [6]:
x = np.random.random((5,4))
x

array([[0.69328536, 0.76713819, 0.30275534, 0.63755589],
       [0.35494828, 0.1933479 , 0.35962161, 0.91529549],
       [0.52901003, 0.71097218, 0.67523933, 0.62128182],
       [0.19016891, 0.6449346 , 0.31737105, 0.13276142],
       [0.83028281, 0.27619717, 0.12705449, 0.83300633]])

In [14]:
y = np.mean(x,axis=1,keepdims=True)

In [15]:
x - y

array([[ 0.09310166,  0.1669545 , -0.29742836,  0.0373722 ],
       [-0.10085504, -0.26245542, -0.09618171,  0.45949217],
       [-0.10511581,  0.07684634,  0.04111349, -0.01284402],
       [-0.13114008,  0.32362561, -0.00393794, -0.18854758],
       [ 0.31364761, -0.24043803, -0.38958071,  0.31637113]])

In [17]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.where(a%2!=0,-1,a)  #just like 

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
# here i have to replace max item from both array and combine both and new arrray
a = np.array([6,3,1,5,9])
b = np.array([3,2,1,7,2])

print(a>b)
print(b>a)


a[b>a] = b[b>a] #here it take perticular index of a and replace with best option of b
a

[ True  True False False  True]
[False False False  True False]


array([6, 3, 1, 7, 9])

In [ ]:
arr1 = np.random.randint(1,10000,40).reshape(8,5)
arr1 = np.random.randint(1,10000,(8,5))
arr1

array([[9878, 9952, 9943, 7501, 9233],
       [  98, 8282, 9648, 1275, 9143],
       [7720, 2951,  790, 3451,  456],
       [1429, 8313, 4574, 1241, 9638],
       [1102, 9989, 2283, 7708, 2267],
       [7346, 5780, 4013, 7703, 4622],
       [4344, 5243, 1630, 7915, 3947],
       [3883, 9813, 5844, 6249, 4983]], dtype=int32)

In [18]:
arr1[:,1::2]

array([[9952, 7501],
       [8282, 1275],
       [2951, 3451],
       [8313, 1241],
       [9989, 7708],
       [5780, 7703],
       [5243, 7915],
       [9813, 6249]], dtype=int32)

In [73]:
(arr1 - arr1.min()) / (arr1.max()-arr1.min())

array([[0.18933624, 0.73090316, 0.14504897, 0.69020675, 0.77431991],
       [0.45723613, 0.33754081, 0.73623504, 0.22644178, 0.62676823],
       [0.88792165, 0.        , 0.48683351, 0.37725789, 0.75212187],
       [0.96713819, 0.25484222, 1.        , 0.42774755, 0.46659412],
       [0.42415669, 0.85429815, 0.4523395 , 0.14776931, 0.1609358 ],
       [0.69281828, 0.03025027, 0.37301415, 0.51621328, 0.93841132],
       [0.91969532, 0.80892274, 0.20674646, 0.46768226, 0.2515778 ],
       [0.93460283, 0.5515778 , 0.31893362, 0.03155604, 0.38628945]])

In [20]:
a = np.array([12,34,40,7,1,0])
a

array([12, 34, 40,  7,  1,  0])

In [ ]:
a.sort()  # permanant operation
a

array([ 0,  1,  7, 12, 34, 40])

In [ ]:
def find(arr,n):
    return a[np.max(len(a)-n)]

n = int(input("Enter the number of max number which you want: "))
find(a,n)


np.int64(1)

In [96]:
# create the following pattern without hardcofing.use only numpy function and the below input array a
a = np.array([1,2,3])
np.repeat(a,3)
np.tile(a,2)

x =np.append(np.repeat(a,3),np.tile(a,2))
y = np.hstack((np.repeat(a,3),np.tile(a,2)))
print(x)
print(y)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3]
