Important Tricks

np.sort

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)

[ 5 71  2 44 90  2 18  4 58 43 39 45 77 86 32]


In [2]:
a = np.sort(a)
a

array([ 2,  2,  4,  5, 18, 32, 39, 43, 44, 45, 58, 71, 77, 86, 90],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,15).reshape(3,5)
b

array([[ 1, 46, 84, 40, 55],
       [ 6, 80, 63, 91,  4],
       [34, 30, 62, 46, 69]], dtype=int32)

In [ ]:
np.sort(b)[::-1]

array([[ 1, 40, 46, 55, 84],
       [ 4,  6, 63, 80, 91],
       [30, 34, 46, 62, 69]], dtype=int32)

In [11]:
np.append(a,20)
a
a

array([ 2,  2,  4,  5, 18, 32, 39, 43, 44, 45, 58, 71, 77, 86, 90],
      dtype=int32)

In [12]:
c = np.arange(10).reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
np.append(c,np.random.random((c.shape[0],1)),axis=1)

array([[0.        , 1.        , 2.        , 3.        , 4.        ,
        0.14325432],
       [5.        , 6.        , 7.        , 8.        , 9.        ,
        0.80902458]])

In [14]:
# we usually uses concatenate function with 2d array
i = np.arange(6).reshape(2,3)
j = np.arange(6,12).reshape(2,3)
print(i)
print(j)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
print(np.concat((i,j),axis=1)) 
print(np.concat((i,j),axis=0))
# Use axis=0 for vertical stacking (rows).
# Use axis=1 for horizontal stacking (columns).

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
np.concatenate((i,j),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
# with help of np.unique() method, we cn get the unique values from an array given as parameter in np.unique() method
x = np.array([1,1,2,2,3,3,4,4,5,5,6,6,8,9,5,2,6,3,8])
np.unique(x)
# we can get the unique array from original array

array([1, 2, 3, 4, 5, 6, 8, 9])

In [17]:
# rare function with 
a = np.arange(25)
a
print(a.shape)
np.expand_dims(a,axis=0).shape
a

(25,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
np.expand_dims(a,axis=1).shape

(25, 1)

In [21]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
a = np.random.randint(1,100,10)

In [24]:
print(a)
# to find values
a[np.where(a>50)]

[81 99  7 55 38 67 52 30 95 80]


array([81, 99, 55, 67, 52, 95, 80], dtype=int32)

In [ ]:
# replace all values > 50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)  # temp check
a

array([81, 99,  7, 55, 38, 67, 52, 30, 95, 80], dtype=int32)

In [28]:
np.where(a%2==0,0,a)

array([81, 99,  7, 55,  0, 67,  0,  0, 95,  0], dtype=int32)

np.argmax

the numpy.argmax() function return indices of the max element of the array in a perticular axis.

In [39]:
a = np.random.randint(1,100,25).reshape(5,5)
a

array([[47, 17, 59,  9, 95],
       [26, 55, 26, 58, 41],
       [49, 40, 87, 38, 38],
       [15, 63, 15, 92, 99],
       [80, 16, 20, 64, 29]], dtype=int32)

In [40]:
np.argmax(a,axis=1) #to find max element  # returns indices

array([4, 3, 2, 4, 0])

In [50]:
b = np.random.randint(1,100,25).reshape(5,5)
b

array([[92, 18, 92, 55, 57],
       [87,  9, 66, 12, 31],
       [88, 62, 86, 28, 82],
       [22,  3, 88, 34,  6],
       [11, 73, 13, 70, 98]], dtype=int32)

In [41]:
np.argmax(b,axis=1) # 1 means row
                    # 0 means col
np.argmin(b,axis=0)

array([0, 2, 2, 0, 1])

In [54]:
a

array([24, 23, 33, 14, 65, 58,  8, 96, 81, 15], dtype=int32)

In [ ]:
np.cumsum(a,axis=0)  # column wise cummulative sum

array([[ 47,  17,  59,   9,  95],
       [ 73,  72,  85,  67, 136],
       [122, 112, 172, 105, 174],
       [137, 175, 187, 197, 273],
       [217, 191, 207, 261, 302]])

In [56]:
np.sum(a)

np.int64(417)

In [57]:
np.cumsum(b)

array([  92,  110,  202,  257,  314,  401,  410,  476,  488,  519,  607,
        669,  755,  783,  865,  887,  890,  978, 1012, 1018, 1029, 1102,
       1115, 1185, 1283])

In [59]:
print(b)
np.cumsum(b,axis=0)

[[92 18 92 55 57]
 [87  9 66 12 31]
 [88 62 86 28 82]
 [22  3 88 34  6]
 [11 73 13 70 98]]


array([[ 92,  18,  92,  55,  57],
       [179,  27, 158,  67,  88],
       [267,  89, 244,  95, 170],
       [289,  92, 332, 129, 176],
       [300, 165, 345, 199, 274]])

In [46]:
print(a)
np.percentile(a,50)
np.median(a)

[[47 17 59  9 95]
 [26 55 26 58 41]
 [49 40 87 38 38]
 [15 63 15 92 99]
 [80 16 20 64 29]]


np.float64(41.0)

np.histogram() is very useful function

In [48]:
# histogram is basically a freq graph(block)
# basically it give number of count which are present in that perticular range
a= np.random.randint(1,50,8)
a

array([19, 38, 49,  6, 43, 34, 35, 40], dtype=int32)

In [49]:
np.histogram(a,bins=[0,10,20,30,40,50])
# 0-10 10-20 20-30 30-40 40-50

(array([1, 1, 0, 3, 3]), array([ 0, 10, 20, 30, 40, 50]))

np.corrcoef()

return pearson product-moment correlation coeffients.


In [50]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [51]:
a

array([19, 38, 49,  6, 43, 34, 35, 40], dtype=int32)

In [ ]:
item = [10,20,41,40,50,60,70,80,90]
np.isin(a,item)

array([False,  True, False, False, False, False, False, False])

In [ ]:
np.flip(a,axis=0)
a[::-1]
# it is a slicing method
# start:stop:step
# filp and slicing

array([40, 35, 34, 43,  6, 49, 38, 19], dtype=int32)

In [54]:
b = np.random.randint(1,25,15).reshape(3,5)
b

array([[11, 16, 10, 11, 10],
       [12,  7, 22, 11,  4],
       [12, 15,  1, 15, 21]], dtype=int32)

In [55]:
np.flip(b,axis=0)

array([[12, 15,  1, 15, 21],
       [12,  7, 22, 11,  4],
       [11, 16, 10, 11, 10]], dtype=int32)

In [ ]:
np.flip(b,axis=1)
b[:] = b[::-1]
# this step describe i can make a peramant reverse array without make it's copy

In [57]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  49,   6,  43,  34,  35,  40], dtype=int32)

In [ ]:
np.delete(a,[0,2,4])  # temp operation

array([530,   6,  34,  35,  40], dtype=int32)

In [59]:
a

array([110, 530,  49,   6,  43,  34,  35,  40], dtype=int32)

Set Function

np.union1d  
np.intersect1d  
np.setdiff1d  
np.setxor1d  
np.in1d

In [62]:
m = np.array([1,2,3,58,5])
n = np.array([6,7,8,9,10])

np.union1d(m,n)

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 58])

In [6]:
np.in1d(m,n) #but always use isin instead of in1d

C:\Users\soura\AppData\Local\Temp\ipykernel_17008\1224809872.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,n) #but always use isin instead of in1d


array([False, False, False, False, False])

In [63]:
m[np.isin(m,58)]

array([58])

In [66]:
print(np.clip(a,a_min=25,a_max=75) )  # 
a

[75 75 49 25 43 34 35 40]


array([110, 530,  49,   6,  43,  34,  35,  40], dtype=int32)

In [13]:
a

array([ 7, 11, 51, 71, 85, 64, 53, 75, 59, 85, 51, 32, 71, 53, 81],
      dtype=int32)