In [1]:
import numpy as np

In [31]:
a = np.random.randint(0,100,(4,3))
print(a)


[[ 6 61 99]
 [69 76 77]
 [57 23 16]
 [15 75 32]]


In [34]:
print(np.sort(a))
# sorting based on 2nd column
a[a[:,-1].argsort()]

# sort based on max of each row
print(np.array(sorted(a,key=lambda x:max(x))))

[[ 6 61 99]
 [69 76 77]
 [16 23 57]
 [15 32 75]]
[[57 23 16]
 [15 75 32]
 [69 76 77]
 [ 6 61 99]]
